### ISSUE TITLE
DAG sync does not support subdirectories

### ISSUE THREAD

**Issue by mbiermans** [datarootsio/terraform-aws-ecs-airflow#15]
In one of our projects, we split our DAGs over subprojects, which means we created directories in the `dags` directory to better reflect this.

Proposed fix:

- modify the sync DAG to use the `aws s3 sync` function from the awscli library, exclude everything and then include only python file (`--exclude=* --include=*.py`)

Thoughts?

edit: I just realised awscli is not an installed library and would need to be installed extra in the ECS definition, which might be suboptimal? I will try to come up with a different way to do this.

**Comment by nicogelders** [comment]
we could install the aws cli in the airflow dockers.

**Comment by nicogelders** [comment]
Could you create a PR with the suggested changes?
