### ISSUE TITLE
AWS provider configuration doesn't work with multi-account terraform cloud setups

### ISSUE THREAD

**Issue by iaingray** [datarootsio/terraform-aws-ecs-airflow#18]
I'm using the module in a multi-account terraform cloud setup where we have a central devops account which then assumes superuser roles into the relevant infrastructure account.

The way we achieve this is with a provider block which looks like the following:

```
provider "aws" {
  region = "eu-west-1"
  allowed_account_ids = [var.account_id]
  assume_role {
    role_arn = data.terraform_remote_state.baseline.outputs.superuser_service_role["arn"]
  }
}
```

When I try to run the module under this setup, I get an error because it's trying to create resources in the devops account, rather than the target account.

I've resolved the problem by just deleting the following from airflow/main.tf:

```
provider "aws" {
  version = "~> 3.12.0"
  region  = var.region
}
```

So that it uses the inherited provider.  Would you like me to do a PR for this change?

**Comment by nicogelders** [comment]
Hey, yes most definitely, just branch it from "open-pr-here". 

Thanks a lot!

**Comment by dpfeif** [comment]
Fixed in latest release.
