### ISSUE TITLE
Support for Airflow 2.0.0

### ISSUE THREAD

**Issue by SheldonGrant** [datarootsio/terraform-aws-ecs-airflow#19]
I am trying to upgrade the ECS airflow to Airflow 2.0.0. I am setting up a new Airflow service for my team and after having tested Airflow 1.10.12 (default) and considering that Airflow 2.0.0 is in stable release, We feel this could mean less headaches down the line. Less upgrade and migration issues that is.

Testing the terraform module, it seems the only real blockers are the `entrypoint_init.sh` and `entrypoint_scheduler.sh` scripts and the use of the pre-Airflow 2.0.0 initdb and other similar commands. As you know airflow 2.0.0. moved to a new command line structure e.g. `airflow db init`.

Any plans to support Airflow 2.0.0. Or perhaps atleast surfacing the providing of `airflow entrypoints` and `airflow.cfg` scripts to the terraform module so that it can be dynamically added?

Given that the module supports a docker based workflow for providing of airflow images, this second suggestion seems logical.

Seems like [ECS terraform resource: ecs.tf](https://github.com/datarootsio/terraform-aws-ecs-airflow/blob/20fcba831f9054d1e6d2f815f8453f855edbd0a9/ecs.tf#L70) would support this dynamic passing of paths to entrypoint scripts. Also, using the [s3 bucket object](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket_object) to copy the files to s3 locations could work.

thoughts? Would greatly appreciate it.

**Comment by nicogelders** [comment]
I will be adding support for airflow 2.0.0 later this week. And I will also add the option to provide your own entrypoint files.

**Comment by nicogelders** [comment]
https://github.com/datarootsio/terraform-aws-ecs-airflow/pull/20
