### ISSUE TITLE
RDS postgres cannot be upgraded from 11.10 to 11.8 

### ISSUE THREAD

**Issue by SheldonGrant** [datarootsio/terraform-aws-ecs-airflow#23]
I have been running in to issues on each of my terraform applies after initial deploy. The database error specifically is problematic as it messes up deploy of a new container, say in the example where package requirements for our airflow server change. The terraform module will fail on trying to update the RDS and no changes to the server will be inacted.

Can you suggest a solution? I haven't seen this error around and would just like to highlight it.

![image](https://user-images.githubusercontent.com/28047198/123939510-7bc9a100-d998-11eb-988f-5be33c934218.png)

**Comment by SheldonGrant** [comment]
@DirksCGM 👀 (for reference)

**Comment by SheldonGrant** [comment]
@nicogelders @samueldumont
Just wanted to highlight a solution for this issue.

- change Terraform RDS auto_minor_version_upgrade == False to stop AWS RDS from automatically upgrading.

https://stackoverflow.com/questions/66245653/aws-rds-database-version-is-different-than-terraform-version

**Comment by frederikdesmedt** [comment]
Hi @SheldonGrant, we've implemented the fix you proposed and also allowed you to set your own postgres version using the `rds_version` variable (among other things). The default engine version is at 12.7 now, so if you want to keep things on 11.10 you can set the `rds_version` at 11.10 yourself.

Thank you for your patience and for the proposed fix!
